Move Dashboard's back-end logic to Lifecycle
TheRacetrack/racetrack pull request #238
Opened 2023-05-05 11:43 UTC by iszulcdeepsense

2023-05-08 13:12 UTC, LookACastle requested changes

2023-05-08 13:12 UTC, LookACastle commented on lifecycle/lifecycle/job/portfolio.py
> +        score -= 1 * newer_versions
This should be interpolated as well. You shouldn't remove a legacy job (that might be legacy for a reason) with a higher priority than a lost job if it's legacy enough.

Also, you should probably be able to escape this scoring as a job somehow. It's all but guaranteed that someone somewhere will be running a mission critical system that's 10 years out of date, and that shouldn't lead to it getting axed.

2023-05-08 14:08 UTC, iszulcdeepsense commented on racetrack_commons/racetrack_commons/auth/__init__.py
It was never intended as renaming. I created this file, but for some reason git / github matched this file as a result of  renaming

2023-05-10 08:35 UTC, LookACastle commented on lifecycle/lifecycle/job/ansi.py
> +    return re.sub(r'\x1b\[\d+(;\d+)?m', '', content)
`strip_ansi_colors` is good too.

2023-05-10 08:38 UTC, LookACastle approved these changes
All my feedback seems to be reacted to and solved, LGTM

2023-05-10 08:48 UTC, merged